In [9]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib as mpl
import locale
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [10]:
df = pd.read_csv('https://app.quotemedia.com/quotetools/getHistoryDownload.csv?&webmasterId=91386&showTrades=true&symbol=SPX&startDay=27&startMonth=3&startYear=2019&endDay=27&endMonth=4&endYear=2019&isRanged=false&maxDownloadYears=10')
df.head(10)

,date,open,high,low,close,volume,changed,changep,adjclose,tradeval,tradevol
0,2019-05-23,2836.70,2836.70,2805.49,2822.24,0,-34.03,-1.19%,2822.24,NaN,0.0
1,2019-05-22,2856.06,2865.47,2851.11,2856.27,0,-8.09,-0.28%,2856.27,NaN,0.0
2,2019-05-21,2854.02,2868.88,2854.02,2864.36,0,24.13,0.85%,2864.36,NaN,0.0
3,2019-05-20,2841.94,2853.86,2831.29,2840.23,0,-19.30,-0.67%,2840.23,NaN,0.0
4,2019-05-17,2858.60,2885.48,2854.23,2859.53,0,-16.79,-0.58%,2859.53,NaN,0.0
5,2019-05-16,2855.80,2892.15,2855.80,2876.32,0,25.36,0.89%,2876.32,NaN,0.0
6,2019-05-15,2820.38,2858.68,2815.08,2850.96,0,16.55,0.58%,2850.96,NaN,0.0
7,2019-05-14,2820.12,2852.54,2820.12,2834.41,0,22.54,0.80%,2834.41,NaN,0.0
8,2019-05-13,2840.19,2840.19,2801.43,2811.87,0,-69.53,-2.41%,2811.87,NaN,0.0
9,2019-05-10,2863.10,2891.31,2825.39,2881.40,0,10.68,0.37%,2881.40,NaN,0.0

In [11]:
priceVec = df["adjclose"].values